### ISSUE TITLE
Jump to Viewpoint submenu does not support Unicode

### ISSUE THREAD

**Issue by janadamec1** [castle-engine/castle-model-viewer#100]
When I define Viewpoint names with non-ansi characters, the Navigation - Jump to Viewpoint submenu shows invalid characters. This can be seen on both Windows and macOS (not tested anywhere else). The file is encoded using UTF-8, and it is correctly stated at the 1st line of the file.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 4.0//EN" "http://www.web3d.org/specifications/x3d-4.0.dtd">
<X3D profile="Interchange" version="4.0"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
     xsd:noNamespaceSchemaLocation="http://www.web3d.org/specifications/x3d-4.0.xsd">
<head>
</head>
<Scene>
	<Viewpoint
		description="Test również ąćęłńóśźżł"
		jump="false"
		position="3.0999999046325684 1.6000000238418579 6.820000171661377"
		orientation="0 1 0 0"
		fieldOfView="0.87300002574920654" />
```

![view3dcodingmenu](https://github.com/user-attachments/assets/4d476bdb-0729-479e-9f38-8508c6e2168c)

Check the attached file (after removing .txt suffix):
[3DScene.x3d.txt](https://github.com/user-attachments/files/16758870/3DScene.x3d.txt)

**Comment by janadamec1** [comment]
I can help with the fix, but I was not successful identifying the proper place and way to fix.

For example, on macOS, should this be somehow fixed around `EntryItem.Caption` in castlewindow_cocoa_menu.inc?
```
      CocoaMenuItem := TCocoaMenuItem.alloc.initWithTitle_action_keyEquivalent(
        NSSTR(SRemoveMnemonics(EntryItem.Caption)),
        ObjCSelector('castleClick:'),
        NSSTR(CocoaKeyEquivalent)
      );
```

**Comment by michaliskambi** [comment]
Thanks! Looks like the menu-creation/updating code doesn't account that characters may be outside of ASCII.

If you'd like to investigate, here's a bunch of information that may be helpful:

All the content we have in Pascal strings should always be UTF-8 (with FPC; or UTF-16 with Delphi, see https://castle-engine.io/coding_conventions#strings_unicode ). It has to be passed on all platforms to the underlying API (WinAPI, Cocoa, etc.) to account for this.

Platforms:

- GTK2: It happens to actually work already with GTK2, i.e. your testcase is OK on Linux. Just because GTK happens to also expect strings in UTF-8. 
    
    ![gtk_menu](https://github.com/user-attachments/assets/dd278126-1373-492d-897b-a499c0f2a63a)

- WinAPI: WinAPI (the default `A` variant) expects all 8-bit strings to be in ANSI encoding. The `W` variant of WinAPI expects input as UTF-16. 

    My personal preference for dealing with WinAPI and international characters is to sidestep the whole "what is ANSI encoding" and just use the `W` functions. So one can just convert string to `UnicodeString` (which is equal `String` on Delphi) and pass this to WinAPI, maybe casting as `PWideChar`. E.g. `StringToUtf16` can be used to write it nicely, see https://github.com/castle-engine/castle-engine/blob/9b5a95116b54371b5210de549f8a400e2652a309/src/base/castlestringutils.pas#L2698 . 

    Our clipboard (copy/paste) and window caption code already do this, e.g. they use `W` variants of WinAPI, and I tested that window captions are OK with local characters, and copy/paste also works OK with local characters.

    Hm, looking at WinAPI code of menu, it should already be correct, https://github.com/castle-engine/castle-engine/blob/master/src/window/windows/castlewindow_winapi_menu.inc uses `AppendMenuW` . Well, but evidently there's something wrong :)

- Cocoa: I also don't know what's wrong. Yes, the lines you point out are key. The `NSSTR(SRemoveMnemonics(EntryItem.Caption))` should be the way to pass Pascal string (with UTF-8) to Cocoa. But then, something is wrong and I don't know what. You can
    1. make sure that `SRemoveMnemonics(EntryItem.Caption)` is UTF-8 encoding of the characters you expect.
    2. make sure that `NSSTR(...)` is the right way to pass UTF-8 as input to Cocoa. 

I'm not sure did I really help you above -- basically, it needs investigation, on both WinAPI and Cocoa. Looking at code, it *should* already be good but evidently it is not.
